builds:
  - id: ff7book
    binary: ff7book
    main: ./cmd/ff7book
    goarch:
      - amd64
      - arm64
      - arm
archives:
  - id: ff7book
    builds:
      - ff7book
    format: zip
    name_template: 'ff7book_{{ .Version }}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}'
